import Head from "next/head";
import { Navbar, Stories, Chart } from "../src/component/modules";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Studext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container-fluid mt-5 pt-5 min-vh-100">
        <div className="row ">
          <div className="col-12 col-lg-8">
            <Stories />
            <div className="statistics mt-4 pb-3">
              <h3>Statistics</h3>
              <Chart />
            </div>
          </div>
          <div className="col-12 col-lg-4 mt-4 mt-lg-0">
            <div className="leaderboard h-100">
              <h3>Peringkat</h3>
              <p>Hasil akhir perolehan nilai try out</p>
              <button className="download">
                <svg
                  width="14"
                  height="14"
                  viewBox="0 0 14 14"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M1 10V10.75C1 11.3467 1.23705 11.919 1.65901 12.341C2.08097 12.7629 2.65326 13 3.25 13H10.75C11.3467 13 11.919 12.7629 12.341 12.341C12.7629 11.919 13 11.3467 13 10.75V10M10 7L7 10M7 10L4 7M7 10V1"
                    stroke="#008FFF"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
                <span className="ms-1">Unduh.CSV</span>
              </button>
              <img src="/throphy.png" alt="trophy" />
              <div className="ranking mt-3">
                <div className="container-rank">
                  <div className="position">1</div>
                  <div className="avatar">
                    <img alt="avatar" />
                  </div>
                  <div>
                    <p>Nevalen Aginda Prasetyo</p>
                  </div>
                  <div className="point">
                    <div>40</div>
                    <div>0</div>
                    <div>0</div>
                  </div>
                  <div className="score"></div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-12"></div>
        </div>
      </div>
    </div>
  );
}
